// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTvlbSyHQA9Q7VTdeJzTwGa5Lcf__fxXw',
    appId: '1:105937566565:web:c435f9555a85e873f2bf8c',
    messagingSenderId: '105937566565',
    projectId: 'society-54fff',
    authDomain: 'society-54fff.firebaseapp.com',
    storageBucket: 'society-54fff.appspot.com',
    measurementId: 'G-E40J4CZKF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkfMi5h5uNfMRZDWBpUSuia6Y0mTEXwJo',
    appId: '1:105937566565:android:f129bc6712ad5620f2bf8c',
    messagingSenderId: '105937566565',
    projectId: 'society-54fff',
    storageBucket: 'society-54fff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP5p_ULeDGB-vc0cd7AErTWfx360tRioU',
    appId: '1:105937566565:ios:8480b317628b5e31f2bf8c',
    messagingSenderId: '105937566565',
    projectId: 'society-54fff',
    storageBucket: 'society-54fff.appspot.com',
    iosClientId: '105937566565-3t4lasqufsp8cidnociu3ea6m23u4svc.apps.googleusercontent.com',
    iosBundleId: 'com.example.societyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP5p_ULeDGB-vc0cd7AErTWfx360tRioU',
    appId: '1:105937566565:ios:93ffa4c56a7f02b7f2bf8c',
    messagingSenderId: '105937566565',
    projectId: 'society-54fff',
    storageBucket: 'society-54fff.appspot.com',
    iosClientId: '105937566565-d9nalp63jg680u6qt9mq9luc8g5fujug.apps.googleusercontent.com',
    iosBundleId: 'com.example.societyApp.RunnerTests',
  );
}
